version: "3.3"

services:
  pynoel-gui-app:
    restart: always
    image: noelmni/pynoel-gui-app:latest
    container_name: pynoel-gui-app
    environment:
      - PUID=1001 # change to $(id -u)
      - PGID=1001 # change to $(id -g)
      - TZ=America/Toronto
    ports:
      - "9999:9999"
    # volumes:
    #   - "./data:/data"