networks:
  textures-app:
    name: textures-app

services:
  textures-app:
    build:
      context: .
    image: noelmni/pynoel-gui-app:latest
    container_name: pynoel-gui-app
    restart: always
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 8G
    ports:
      - "9999:9999"
    volumes:
      - "./io:/data"
    networks:
      textures-app:
