version: "3.3"

services:
  pynoel-gui-app:
    container_name: pynoel-gui-app
    environment:
      - PUID=2551
      - PGID=200
      - TZ=America/Toronto
      - DISPLAY=${DISPLAY}
      - /tmp/.X11-unix:/tmp/.X11-unix
    # ports:
    #   - "5800:5800"
    image: neuressence/pynoel-gui-app:latest
    restart: always
    volumes:
      - "${PWD}:/data"
