[workspace]
authors = ["Ravnoor Gill <ravnoor.gill@mcgill.ca>"]
channels = ["https://repo.prefix.dev/noel-forge", "conda-forge", "main"]
description = "Plotly Dash app to generate textures maps from MRI"
name = "noelTexturesPy"
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
version = "0.2.3"
# channel-priority = "disabled"

[tasks]
app = { cmd = "python -m src.noelTexturesPy.app" }
fmt = "ruff"
lint = "pylint"
test = { cmd = "python -m pytest tests/ -n auto -v" }
test-unit = { cmd = "python -m pytest tests/test_noelTexturesPy.py -n auto -vvv" }
test-webapp = { cmd = "python -m pytest tests/test_webapp.py -n auto -v" }
test-all = { cmd = "bash tests/run_tests.sh" }

[tasks.test-app]
depends-on = [
  { task = "test", environment = "dev" },
]

[dependencies]
numpy = ">=2.3.5,<3"
scipy = ">=1.17.1,<2"
pandas = ">=3.0.3,<4"
matplotlib = ">=3.10.9,<4"
pillow = ">=12.2.0,<13"
flask = ">=3.1.3,<4"
nibabel = ">=5.4.2,<6"
pyyaml = ">=6.0.3,<7"
webcolors = ">=25.10.0,<26"

[pypi-dependencies]
noel-textures-py = { path = ".", editable = true }
dash = ">=4.2.0, <5"
dash-bootstrap-components = ">=2.0.4, <3"
chart-studio = ">=1.1.0, <2"

[feature.ants]
channels = [ "https://repo.prefix.dev/noel-forge", {channel = "main", priority = -1}]
dependencies = { antspyx = ">=0.6.3,<0.7" }
tasks = {download-models = { cmd = "python download-models.py", default-environment = "ants", cwd = "scripts" }}

[feature.ants.pypi-dependencies]
antstorch = { git = "https://github.com/ravnoor/ANTsTorch.git", branch = "textures-deps"}
# antstorch = { path = "./deps/ANTsTorch", editable = true}

[feature.build-ants.dependencies]
rattler-build = ">=0.66.0,<0.67"

[feature.dev.pypi-dependencies]
datalad = ">=1.6.0, <2"

[feature.dev.dependencies]
prek = ">=0.4.4, <1"

[feature.test.pypi-dependencies]
mypy = ">=2.1.0, <3"
pytest = "*"
pyprojroot = ">=0.3.0, <0.4"
pytest-xdist = ">=3.8.0, <4"


[environments]
build-ants = {features = ["build-ants"], no-default-feature = true}
dev = {features = ["ants", "dev", "test"]}
prod = {features = ["ants"]}
default = {features = ["ants", "test"]}
