name: antspyx
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.14.0a0
  - pandas>=1.5.2,<2.0.0
  - pyyaml>=6.0,<7.0
  - numpy>1.23.5,<=2.0.1
  - statsmodels>=0.13.2,<0.14.0
  - webcolors>=1.12,<1.14
  - matplotlib<4.0.0
  - Pillow>=9.3.0,<10.0.0
  - request>=2.28.1,<3.0.0
  - pip
