# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: ANTs
  version: 2.6.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/ANTsX/ANTs/archive/v${{ version }}.tar.gz
  sha256: 9e8bf4e6e336c2a8aa6e38159258549a92810e605b135599ea760970f4919438

build:
  number: 0
  script:
    - mkdir build
    - cd build
    - if: unix
      then:
        - cmake -G Ninja ${CMAKE_ARGS} -DANTS_SUPERBUILD:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_PREFIX:STRING=${PREFIX} -DCMAKE_PREFIX_PATH:STRING=${PREFIX} -DRUN_SHORT_TESTS:BOOL=ON -DRUN_LONG_TESTS:BOOL=OFF -DUSE_SYSTEM_ITK:BOOL=ON ${SRC_DIR}
        - cmake --build . --parallel ${CPU_COUNT} --target install
        - if [[ "${CONDA_BUILD_CROSS_COMPILATION:-}" != "1" || "${CROSSCOMPILING_EMULATOR}" != "" ]]; then ctest --parallel ${CPU_COUNT} --extra-verbose --output-on-failure; fi
    - if: win
      then:
        - set "CMAKE_ARGS=%CMAKE_ARGS% -DCMAKE_INSTALL_LIBDIR:STRING=%LIBRARY_LIB% -DCMAKE_INSTALL_PREFIX:STRING=%LIBRARY_PREFIX% -DCMAKE_PREFIX_PATH:STRING=%LIBRARY_PREFIX% -DBUILD_SHARED_LIBS:BOOL=ON -DANTS_SUPERBUILD:BOOL=OFF -DUSE_SYSTEM_ITK:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release"
        - cmake %CMAKE_ARGS% %SRC_DIR%
        - cmake --build . --config Release --parallel %CPU_COUNT% --target install

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake >=3.16.3
    - ninja
  host:
    - libboost-headers
    - libitk-devel
  run:
    - ${{ pin_compatible('libitk', lower_bound='x.x', upper_bound='x.x') }}

tests:
  - script:
      - antsRegistration --help

about:
  license: Apache-2.0
  license_file: COPYING.txt
  summary: >
    ANTs computes high-dimensional mappings to capture the statistics of brain structure and function
  homepage: https://stnava.github.io/ANTs/
  repository: https://github.com/ANTsX/ANTs/wiki
  documentation: http://stnava.github.io/ANTsDoc
