name: Code quality

on:
  push:
    branches:
      - dev
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 4 * * *"

env:
  FORCE_COLOR: 1

jobs:
  check:
    name: tox env ${{ matrix.tox_env }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tox_env:
          - format
          - lint
          - types

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v8
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install tox
        run: uv tool install tox --with tox-uv

      - name: Run check for tox env "${{ matrix.tox_env }}"
        run: tox -e ${{ matrix.tox_env }}
