name: Publish Docker image

on:
  push:
    branches:
      - 'docker_ci'

jobs:
  base_push_to_registry:
    name: Push Docker pynoel-gui-base image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: noelmni/pynoel-gui-base
          tags: |
            type=semver,pattern={{version}}
            # dynamically set the branch name as a prefix
            type=sha,prefix={{branch}}-
            # dynamically set the branch name
            type=raw,value={{branch}}-latest
          labels: |
            org.opencontainers.image.title="noelTexturesPy base-image"
            org.opencontainers.image.description="base-image for noelTexturesPy"
            org.opencontainers.image.vendor="Neuroimaging of Epilepsy Laboratory at McGill University"
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: base-docker-image/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  main_push_to_registry:
    name: Push Docker pynoel-gui-app image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: noelmni/pynoel-gui-app
          tags: |
            type=semver,pattern={{version}}
            # dynamically set the branch name as a prefix
            type=sha,prefix={{branch}}-
            # dynamically set the branch name
            type=raw,value={{branch}}-latest
          labels: |
            org.opencontainers.image.title="noelTexturesPy"
            org.opencontainers.image.description="Dash app to generate textures maps from MRI using Advanced Normalization Tools"
            org.opencontainers.image.vendor="Neuroimaging of Epilepsy Laboratory at McGill University"        
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}