name: Test Docker image builds for PRs

on:
  pull_request:
    types: [opened, reopened]

jobs:
  base_image:
    name: Test Docker pynoel-gui-base build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: noelmni/pynoel-gui-base
          tags: |
            # dynamically set the branch name as a prefix/suffix
            type=sha,prefix={{ github.ref_name }}-,suffix=test_CI
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: base-docker-image/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  main_image:
    name: Test Docker pynoel-gui-app build
    needs: base_image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: noelmni/pynoel-gui-app
          tags: |
            # dynamically set the branch name as a prefix/suffix
            type=sha,prefix={{ github.ref_name }}-,suffix=test_CI   
   
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Set BASE_SHORT_SHA_TAG variable to build the subsequent app image
        run: |
          echo "BASE_SHORT_SHA_TAG=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
          echo "BASE_SHORT_SHA_TAG equals ${{env.BRANCH_NAME}}-${{env.BASE_SHORT_SHA_TAG}}-test_CI"

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: push
          build-args: |
            BASE_SHORT_SHA_TAG=${{ env.BRANCH_NAME }}-${{ env.BASE_SHORT_SHA_TAG }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
