context:
  name: antspyx
  version: 0.6.2

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - git: https://github.com/ANTsX/ANTsPy.git
    # tag: v${{ version }}
    rev: ab74a5376d8cd6b9c274d17476ea3062d3d48f73
    patches:
      - itk_patch.diff

build:
  # script: build.sh
  script:
    content: |
      export CMAKE_BUILD_PARALLEL_LEVEL=${CMAKE_BUILD_PARALLEL_LEVEL:-$CPU_COUNT}
      echo "Building with CPU_COUNT=${CPU_COUNT}"
      ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    # env:
    #   CPU_COUNT: ${{ env.get("CPU_COUNT", default="40") }}
  skip:
    - win

requirements:
  build:
    - ${{ compiler('cxx') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - if: linux
      then:
        - make
    - if: win
      then:
        - ninja
    - scikit-build
    - cmake >=3.18
    - if: not win
      then:
        - ants
  host:
    - python
    - scikit-build-core >=0.4.3
    - pip
    - libpng
    - libitk-devel
    - nanobind >=1.3.2
  run:
    - python
    - pandas
    - pyyaml
    - numpy <=2.0.1
    - statsmodels
    - webcolors
    - matplotlib-base
    - pillow
    - requests
    - scikit-learn
    - scipy <1.16
    - pytest
    - pygments

tests:
  - python:
      imports:
        - ants
      pip_check: true
  - script:
      - bash tests/run_tests.sh
    requirements:
      run:
        - python
        - pytest
        - pygments
    # extra files to be copied to the test folder from the recipe or source directory
    files:
      source:
        - tests/

about:
  homepage: https://antspyx.readthedocs.io/
  summary: A fast medical imaging analysis library in Python with algorithms for registration, segmentation, and more.
  license: Apache-2.0
  license_file: LICENSE
